contracts/urls.py
from django.urls import path
from .views import ListContracts, DetailContract, CreateContract, EditContract, DeleteContract


# Add namespace to urls
app_name = 'contracts'

urlpatterns = [
    path('', ListContracts.as_view(), name='list-contracts'),
    path('<uuid:contract_id>/', DetailContract.as_view(), name='detail-contract'),
    path('create/', CreateContract.as_view(), name='create-contract'),
    path('<uuid:contract_id>/edit/', EditContract.as_view(), name='edit-contract'),
    path('<uuid:contract_id>/delete/', DeleteContract.as_view(), name='delete-contract'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, HomeCreate, HomeEdit
from django.shortcuts import redirect


urlpatterns = [
    path('', lambda request: redirect('home_view', permanent=True)),
    path('home/', HomeView.as_view(), name='home_view'),
    path('index/', lambda request: redirect('home_view', permanent=True)),
    path('index.html', lambda request: redirect('home_view', permanent=True)),
    path('home/edit/', HomeEdit.as_view(), name='home_edit'),
    path('home/create/', HomeCreate.as_view(), name='home_create'),
]

main/urls.py
# main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import LoginView, SignupView, LogoutView, PasswordResetRequestView, PasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('blogs.urls')),
    path('', include('applications.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls.orders')),
    path('customers/', include('orders.urls.customers')),
    path('contracts/', include('contracts.urls')),
    path('', include('jobs.urls')),
    path('', include('companies.urls')),
    path('forums/', include('forums.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('generate-prt/', PasswordResetRequestView.as_view(), name='generate_prt'),
    path('reset-password/<str:token>/', PasswordResetView.as_view(), name='reset_password'),
    path('profile/', include('profiles.urls')), 
]

pengin_pi_2/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

contracts/models.py
from django.db import models
import uuid

from orders.models import Customer


class Contract(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, null=False)
    type = models.CharField(max_length=100)
    content = models.TextField()
    service_date = models.DateField(null=True)
    expiration_date = models.DateField(null=True)

    def __str__(self):
        return f"Contract {self.type} for {self.customer.name}"

    class Meta:
        ordering = ['-service_date', 'customer']

contracts/forms.py
from django import forms

from .models import Contract


class ContractForm(forms.ModelForm):

    service_date = forms.DateField(widget=forms.SelectDateWidget)
    expiration_date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Contract
        fields = ['customer', 'type', 'content', 'service_date', 'expiration_date',]

contracts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from util.security.auth_tools import is_admin_provider, is_admin_required

from .models import Contract
from .forms import ContractForm
from orders.models import Customer


class ListContracts(View):
    template_name = "contracts/contract_list.html"

    @method_decorator(login_required)
    @method_decorator(is_admin_provider)
    def get(self, request, is_admin):

        contracts = Contract.objects.all()

        paginator = Paginator(contracts, 9)
        page_number = request.GET.get("page", 1)
        page_contracts = paginator.get_page(page_number)

        return render(request, self.template_name, {
            "is_admin": is_admin,
            "page_contracts": page_contracts,
            "primary_title": "Contracts",
        })


# Display contract details
class DetailContract(View):
    template_name = "contracts/contract_detail.html"

    @method_decorator(login_required)
    @method_decorator(is_admin_provider)
    def get(self, request, contract_id, is_admin):
        contract = get_object_or_404(Contract, id=contract_id)

        return render(request, self.template_name, {
            "is_admin": is_admin,
            "contract": contract,
            "primary_title": f"{contract}",
        })


class CreateContract(View):
    template_name = "contracts/contract_form.html"

    def get_context_data(self):
        customers = Customer.objects.all()

        return {
            "primary_title": "Create Contract",
            "action": "create",
            "form": ContractForm(),
            "customers": customers,
        }

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = ContractForm(request.POST)

        if form.is_valid():
            new_contract = form.save()
            return redirect('contracts:detail-contract', contract_id=new_contract.id)

        context = self.get_context_data()
        context['form'] = form
        return render(request, self.template_name, context)


class EditContract(View):
    template_name = "contracts/contract_form.html"

    def get_context_data(self, contract):
        customers = Customer.objects.all()

        return {
            "primary_title": "Edit Contract",
            "action": "update",
            "form": ContractForm(instance=contract),
            "customers": customers,
            "contract": contract,
        }

    @method_decorator(login_required)
    @method_decorator(is_admin_required)
    def get(self, request, contract_id, *args, **kwargs):
        contract = get_object_or_404(Contract, id=contract_id)
        context = self.get_context_data(contract)
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    @method_decorator(is_admin_required)
    def post(self, request, contract_id, *args, **kwargs):
        contract = get_object_or_404(Contract, id=contract_id)
        form = ContractForm(request.POST, instance=contract)

        if form.is_valid():
            form.save()
            return redirect('contracts:detail-contract', contract_id=contract.id)

        context = self.get_context_data(contract)
        context['form'] = form
        return render(request, self.template_name, context)


class DeleteContract(View):
    template_name = "contracts/contract_confirm_delete.html"

    @method_decorator(login_required)
    @method_decorator(is_admin_required)
    def get(self, request, contract_id):
        contract = get_object_or_404(Contract, id=contract_id)
        context = {
            "primary_title": f"Delete Contract",
            "contract": contract,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    @method_decorator(is_admin_required)
    def post(self, request, contract_id):
        contract = get_object_or_404(Contract, id=contract_id)
        contract.delete()
        return redirect('contracts:list-contracts')

contracts/templates/contracts/contract_confirm_delete.html
{% extends "layout/fullPageScroll.html" %}

{% block pageContent %}
    <p>Do you really want to delete this contract?</p>
    <p>{{ contract }}</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url "contracts:detail-contract" contract.id %}">
            <button class="primary-button" type="button">Cancel</button>
        </a>
        <button class="primary-button" type="submit">Delete</button>
    </form>
{% endblock %}

contracts/templates/contracts/contract_detail.html
{% extends "layout/fullPageScroll.html" %}
{% load markdownit %}

{% block pageDropDowns %}
  {% if is_admin %}
    <a href="{% url 'contracts:edit-contract' contract.id %}">Edit Contract</a>
    <a href="{% url 'contracts:delete-contract' contract.id %}">Delete Contract</a>
  {% endif %}
{% endblock %}

{% block pageContent %}
    <div class="commonmark"><p>Customer: <a href="{% url "customers:detail-customer" contract.customer.id %}">{{ contract.customer }}</a></p></div>
    <div><p>Contract type: {{ contract.type }}</p></div>
    <div><p>Service date: {{ contract.service_date|date:"M d, Y" }}</p></div>
    <div><p>Expiration date: {{ contract.expiration_date|date:"M d, Y" }}</p></div>
    <div><p>Content: {{ contract.content|markdownit }}</p></div>

{% endblock %}

contracts/templates/contracts/contract_form.html
{% extends "layout/fullPageScroll.html" %}
{% load static %}

{% block pageContent %}
    <form class="form" method="POST">
        {% if form.errors %}
            <div class="alert alert-danger">
            {% for error in form.errors %}
                <ul>
                    <li>{{ error}}</li>
                </ul>
            {% endfor %}
            </div>
        {% endif %}
        {% csrf_token %}
        <div class="contract-edit-container">
            <div class="form-section">
                {{ form.customer.label_tag }}
                {{ form.customer }}
            </div>
            <div class="form-section">
                {{ form.type.label_tag }}
                {{ form.type }}
            </div>
            <div class="form-section contract-edit-description ">
                {{ form.content.label_tag }}
                {{ form.content }}
            </div>
            <div class="form-section">
                {{ form.service_date.label_tag }}
                {{ form.service_date }}
            </div>
            <div class="form-section">
                {{ form.expiration_date.label_tag }}
                {{ form.expiration_date }}
            </div>
        </div>

        {% if action == "update" %}
            <a href="{% url "contracts:detail-contract" contract.id %}">
                <button class="primary-button" type="button">Cancel</button>
            </a>
                <button class="primary-button" type="submit">Save changes</button>
        {% else %}
            <a href="{% url "contracts:list-contracts" %}">
                <button class="primary-button" type="button">Cancel</button>
            </a>
            <button class="primary-button" type="submit">Add Contract</button>
        {% endif %}

    </form>

{% endblock %}

contracts/templates/contracts/contract_list.html
{% extends "layout/alternating_color_table.html" %}

{% block pageDropDowns %}
    <a href="{% url "contracts:create-contract" %}">New Contract</a>
{% endblock %}


{% block tableContent %}
    <thead>
        <tr>
            <th>Contract ID</th>
            <th>Customer</th>
            <th>Type</th>
            <th>Service Date</th>
            <th>Expiration Date</th>
        </tr>
    </thead>
    <tbody>
        {% for contract in page_contracts %}
            <tr>
                <td><a href="{% url 'contracts:detail-contract' contract.id %}">{{ contract.id }}</a></td>
                <td>{{ contract.customer }}</td>
                <td>{{ contract.type }}</td>
                <td>{{ contract.service_date|date:"F d, Y" }}</td>
                <td>{{ contract.expiration_date|date:"F d, Y" }}</td>
            </tr>
        {% endfor %}
    </tbody>
{% endblock %}