blogs/urls.py
from django.urls import path
from blogs.views import BlogsListView, BlogPostDetailView, BlogPostCreateView, BlogPostEditView, BlogPostDeleteView

app_name = 'blogs'

urlpatterns = [
    path('blog', BlogsListView.as_view(), name='blogs'),
    path('blogs', BlogsListView.as_view(), name='blogs'),
    path('blogs.html', BlogsListView.as_view(), name='blogs'),
    path('blogs/<uuid:pk>/', BlogPostDetailView.as_view(), name='blog_post'),
    path('blogs/<uuid:pk>/edit/', BlogPostEditView.as_view(), name='edit_blog_post'),
    path('blogs/<uuid:pk>/delete/',
         BlogPostDeleteView.as_view(), name='delete_blog_post'),
    path('blogs/create/', BlogPostCreateView.as_view(), name='create_blog_post'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, HomeCreate, HomeEdit
from django.shortcuts import redirect


urlpatterns = [
    path('', lambda request: redirect('home_view', permanent=True)),
    path('home/', HomeView.as_view(), name='home_view'),
    path('index/', lambda request: redirect('home_view', permanent=True)),
    path('index.html', lambda request: redirect('home_view', permanent=True)),
    path('home/edit/', HomeEdit.as_view(), name='home_edit'),
    path('home/create/', HomeCreate.as_view(), name='home_create'),
]

main/urls.py
# main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import LoginView, SignupView, LogoutView, PasswordResetRequestView, PasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('blogs.urls')),
    path('', include('applications.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls.orders')),
    path('customers/', include('orders.urls.customers')),
    path('contracts/', include('contracts.urls')),
    path('', include('jobs.urls')),
    path('', include('companies.urls')),
    path('forums/', include('forums.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('generate-prt/', PasswordResetRequestView.as_view(), name='generate_prt'),
    path('reset-password/<str:token>/', PasswordResetView.as_view(), name='reset_password'),
    path('profile/', include('profiles.urls')), 
]

pengin_pi_2/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blogs/models.py
from django.db import models, transaction
import uuid
from django.utils import timezone


class BlogPost(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, unique=True)
    date = models.DateTimeField(default=timezone.now)
    content = models.TextField(blank=True)
    tags = models.CharField(max_length=150,  blank=True)
    method = models.CharField(
        max_length=10, default='ERROR')

    # this will need to get replaced by db triggers OR Django Signals
    # If bulk actions are involved
    def save(self, *args, **kwargs):
        save_method = self.method
        with transaction.atomic():
            # Do backup of current row values first
            # DELETE is included because we will call save with save_method delete before calling delete
            if save_method == "EDIT" or save_method == "DELETE":
                original_post = BlogPost.objects.get(pk=self.pk)
                post_backup = BlogHistory(post_id=original_post.id, title=original_post.title,
                                          date=original_post.date, content=original_post.content, method=original_post.method, tags=original_post.tags)
                post_backup.save()
            # Else, if this is a newly created row don't save to backup table yet

            # save to this blog post table regardless
            super().save(*args, **kwargs)

            # if this is a pre-delete save,  we need to make sure the row we just saved in blogpost, which records
            # 1) The action/method: "DELETE"
            # 2) The time of the deletion
            # ... is saved into the bloghistory,  because our delete_post view is going to delete this information
            if save_method == 'DELETE':
                post_backup = BlogHistory(post_id=self.id, title=self.title,
                                          date=self.date, content=self.content, method=self.method, tags=self.tags)
                post_backup.save()

    def __str__(self):
        return str(self.title)


class BlogHistory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    post_id = models.UUIDField(db_index=True)
    title = models.CharField(max_length=100,  default='Error Getting Title')
    date = models.DateTimeField(default=timezone.now)
    content = models.TextField(blank=True)
    tags = models.CharField(max_length=150, blank=True)
    method = models.CharField(
        max_length=10, default='ERROR')

blogs/forms.py
# blogs/forms.py

from django import forms
from blogs.models import BlogPost


class BlogForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        # LIST of fields to hide.
        # Don't make it an attribute of BlogForm,  we don't want these fields in the template at all
        # and the form gets passed to the template
        remove_fields = kwargs.pop('remove_fields', [])
        # DICT with fields to prefill and their prefill data
        self.prefill_data = kwargs.pop('prefill_data', {})
        super().__init__(*args, **kwargs)

        # It only makes sense to remove populate the data once we remove the fields
        for field in remove_fields:
            self.fields.pop(field)

        for field_name,  value in self.prefill_data.items():
            if field_name in self.fields:
                self.initial[field_name] = value

    # Set values for fields,  - useful when you want
    # to add in new fields that weren't included in the form
    # and wouldn't have gone through form validation.
    # For example, in blogs, don't need the Method field to
    # ever be on the template version of the form,  and I don't
    # want users to be able to edit the date of the blog post.
    def set_cleaned_data_field(self, field, value):
        # if we ever need validation logic... can
        # check here
        self.cleaned_data[field] = value

    class Meta:
        model = BlogPost
        fields = ['title',
                  'content', 'tags']
        widgets = {'content': forms.Textarea(attrs={'cols': 120, 'rows': 40})}

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from util.security.auth_tools import is_admin_required #, is_admin_provider, user_group_provider
from blogs.forms import BlogForm
from blogs.models import BlogPost, BlogHistory, transaction
from main.models.users import User
# Assuming you have a pagination utility
# Define the blog post view


# Define the blog view

'''
TODO: Remove user and roles.  We are not checking authors or usernames, nor roles.  
Just use is_admin_provider to send is_admin to views and lock down methods that require admin with the is_admin decorator.
These classes and methods are overly complicated, I'm not going to try to fix them, I would start over.

'''


class BlogsListView(ListView):
    queryset = BlogPost.objects.all()
    template_name = 'blogs.html'
    model = BlogPost
    context_object_name = 'blog_posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        is_admin = self.request.user.is_authenticated and self.request.user.validated and self.request.user.is_staff
        context['is_admin'] = is_admin
        context['left_title'] = 'Blog Posts'
        context['primary_title'] = 'Blog'
        blog_posts = self.queryset.order_by('date')
        page_number = self.request.POST.get(
            'page-number', 1) if self.request.method == "POST" else self.request.GET.get('page', 1)
        context['page_number'] = page_number
        paginator = Paginator(blog_posts, 10)
        posts = paginator.get_page(page_number)
        context['posts'] = posts
        return context


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blogpost.html'
    form_class = BlogForm
    context_object_name = 'blog_post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # perhaps this should be refactored to use self.object instead?
        blog_post = get_object_or_404(BlogPost, pk=self.kwargs.get('pk'))

        edit_info = get_last_edit_info(blog_post)
        #author_id, create_date, is_create_missing = author_info
        

        if edit_info:
            edited_date = edit_info
            #edited_by = User.objects.get(id=edited_by_id).name
        else:
            edited_date = ''
            #edited_by = ''

        blog_posts = BlogPost.objects.all().order_by('date')
        paginator = Paginator(blog_posts, 10)

        page = self.request.GET.get("page", 1)
        posts = paginator.get_page(page)
        is_admin = self.request.user.is_authenticated and self.request.user.validated and self.request.user.is_staff

        context['posts'] = posts
        context['post'] = blog_post
        #context['is_create_missing'] = is_create_missing
        #context['author'] = author
        #context['blog_author_date'] = create_date
        #context['edited_by'] = edited_by
        context['blog_edited_date'] = edited_date
        context['page'] = page
        context['is_admin'] = is_admin   # Assuming you have authentication
        return context


@method_decorator(is_admin_required, name='dispatch')
class BlogPostCreateView(LoginRequiredMixin, CreateView):

    model = BlogPost
    form_class = BlogForm
    template_name = 'create_blog_post.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request):
        form = BlogForm(request.POST)
        if form.is_valid():
            # add these fields to the form
            blog_post = form.save(commit=False)
            blog_post.method = 'CREATE'
            #blog_post.user = request.user
            # date will be auto-filled by data model with "now"

            # this should just save a blank '[]' if there are no groups
            #query_groups = request.user.groups.all()
            #blog_post.roles = list(query_groups.values('pk', 'name'))
            # note comment over equivalent line in Blog Post Deletion
            #blog_post.roles.append({"pk": -2, "name": "STAFF"})
            blog_post.save()
            return HttpResponseRedirect(reverse_lazy('blogs:blog_post', kwargs={'pk': blog_post.id}))

    def get(self, request, *args, **kwargs):
        form = BlogForm()
        form_rendered_for_create = form.render("configure_blog_form.html")
        return render(request, self.template_name, {'form': form_rendered_for_create, 'is_admin': True})


@method_decorator(is_admin_required, name='dispatch')
class BlogPostEditView(LoginRequiredMixin, UpdateView):
    model = BlogPost
    form_class = BlogForm
    template_name = 'edit_blog_post.html'
    context_object_name = 'blog_post'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        post_id = self.kwargs.get('pk')
        blog_post = get_object_or_404(BlogPost, id=post_id)
        form = BlogForm(request.POST, instance=blog_post)
        if form.is_valid():
            blog_post = form.save(commit=False)
            # specify this is an edited record
            blog_post.method = 'EDIT'
            #blog_post.user = request.user
            blog_post.date = timezone.now()
            #query_groups = request.user.groups.all()
            #blog_post.roles = list(query_groups.values('pk', 'name'))
            # note comment over equivalent line in Blog Post Deletion
            #blog_post.roles.append({"pk": -2, "name": "STAFF"})
            blog_post.save()
            return HttpResponseRedirect(reverse_lazy('blogs:blog_post', kwargs={'pk': post_id}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # perhaps should be refactored to use self.object?
        blog_post = get_object_or_404(BlogPost, pk=self.kwargs.get('pk'))
        form = BlogForm(instance=blog_post)
        form_rendered_for_edit = form.render(
            "configure_blog_form.html")
        context['form'] = form_rendered_for_edit
        context['is_admin'] = True
        context['pk'] = self.kwargs.get('pk')
        return context


@method_decorator(is_admin_required, name='dispatch')
class BlogPostDeleteView(LoginRequiredMixin, DeleteView):
    model = BlogPost

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        post_id = self.kwargs.get('pk')
        blog_post = get_object_or_404(BlogPost, id=post_id)
        blog_post.method = 'DELETE'
        #blog_post.user = request.user
        blog_post.date = timezone.now()
        #query_groups = request.user.groups.all()
        #blog_post.roles = list(query_groups.values('pk', 'name'))
        # Since at this point only Staff can perform Deletes,  append the
        # Staff role for our records.
        # (Note the negative pk,  which will never exist as an id -
        # - no Staff group exists at this point,  but we want to note
        # that a Staff member did this.
        #blog_post.roles.append({"pk": -2, "name": "STAFF"})
        with transaction.atomic():
            blog_post.save()
            blog_post.delete()
        return HttpResponseRedirect(reverse_lazy('blogs:blogs'))


# utility methods
def get_create_info(blog_post):
    author = ''
    oldest_date = ''
    is_create_missing = False
    if blog_post.method == 'CREATE':
        #author = blog_post.user.id
        oldest_date = blog_post.date

    else:
        blog_post_history = BlogHistory.objects.filter(
            post_id=blog_post.id,  method="CREATE")
        # there should be only one value.
        # we will set a flag if there is no row with method 'CREATE'  in blog history
        oldest_post = blog_post_history.first()
        if oldest_post:
            #author = oldest_post.user
            oldest_date = oldest_post.date
        else:
            # DBAs TAKE NOTE: If a DBA archives or deleted some older blog history
            # then the row with the blog creation date/original post author could have
            # been deleted and will not be available now!
            is_create_missing = True
            author = 'NOT FOUND'
            oldest_date = 'DATE NOT FOUND'

    return (author, oldest_date, is_create_missing)


def get_last_edit_info(blog_post):
    if blog_post.method != 'CREATE':

        if blog_post.method == 'EDIT':
            # Last edit information is already in blog_post
            edit_date = blog_post.date
            #last_edit_user = blog_post.user.id
        elif blog_post.method == 'DELETE':
            # Likely means A DBA restored a deleted row from history,  with the latest history record,
            # which would have method value: 'DELETE'.
            # (It's preferable to get the first history row with 'EDIT' instead)
            # So, get the first Blog history row with method = 'EDIT'
            blog_post_history = BlogHistory.objects.filter(
                post_id=blog_post.id, method="EDIT")
            last_edit = blog_post_history.order_by("-date").first()
            edit_date = last_edit.date
            #last_edit_user = last_edit.user

        return (edit_date)
    # If row was just created,  no edit information is available.
    return None

blogs/templates/blogpost.html
{% extends "layout/horizontal_split.html" %}
{% load markdownit %}

{% block tags %}
  {% if post.tags %}
      <meta name="keywords" content="{{ post.tags|escape }}">
  {% endif %}
{% endblock %}

{% block pageDropDowns %}
  {% if is_admin %}
    <a href="{% url 'blogs:edit_blog_post' post.id %}">Edit Post</a>
    <form method="post" action="{% url 'blogs:delete_blog_post' post.id %}">
      {% csrf_token %}
      <button type="submit" onclick="return confirm('Are you sure you want to delete this post?')">Delete</button>
    </form> 
    <a href="{% url 'blogs:blogs' %}">Blogs Home</a>
  {% endif %}
{% endblock %}

{% block leftContent %}
  {% include "link_list.html" %}
{% endblock %}

{% block rightContent %}
 {% comment %} Worked with Gemini to get some code to manage UTC-to-local timezone conversion {% endcomment %}
 <script>
  function convertUTCToLocal(utcTime) {
    const utcMillis = new Date(utcTime).getTime();
    const localDate = new Date(utcMillis);
    return localDate.toLocaleString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
      hour12: true
    });
  
  }
</script>
    <h3 class="blog-post-title">{{ post.title|escape }}</h3>
    <article class="blog-article">
      {% if is_create_missing %}
      <p style="color: red;" >  
       Blog Creation Date / Original Author not found!
      </p>
      {% endif %}
      <p class="blog-author-date"> Originally Posted On: <span id="blog-post-original-date"></span> </b> | Author: {{ author|escape }} </p>
      <script>
        var utcTime = new Date('{{ blog_author_date|date:"c" }}');
        var localTime = convertUTCToLocal(utcTime);
        document.getElementById('blog-post-original-date').textContent = localTime;
      </script>
      {% if blog_edited_date  %}
        <p class="blog-author-date"> Last Edit:  <span id="blog-post-edited-date"></span>| Edited By: {{ edited_by|escape }} </p>
        <script>
          var utcTime = new Date('{{ blog_edited_date|date:"c" }}');
          var localTime = convertUTCToLocal(utcTime);
          document.getElementById('blog-post-edited-date').textContent = localTime;
        </script>
      {% endif %}
      <div class="commonmark">
        {{ post.content|markdownit }}
      </div>
    </article>
{% endblock %}

blogs/templates/blogs.html
{% extends "layout/horizontal_split.html" %}

{% block pageDropDowns %}
  {% if is_admin %}
    <a href="{% url 'blogs:create_blog_post' %}">New Blog Post</a>
  {% endif %}
{% endblock %}

{% block leftContent %}
    {% include "link_list.html" %}
{% endblock %}

{% block rightContent %}
    <p>Please use the links to navigate to individual blog posts.</p>
{% endblock %}

blogs/templates/configure_blog_form.html
{% for field in form %}
    <div class="fieldWrapper">
        <p>{{ field.errors }}</p>
        <p>{{ field.label_tag }}</p>
        <p>{{ field }}</p>
    </div>
{% endfor %}

blogs/templates/configure_form_for_create.html
{% for field in form %}
    <div class="fieldWrapper">
        <p>{{ field.errors }}</p>
        <p>{{ field.label_tag }}</p>
        <p>{{ field }}</p>
    </div>
{% endfor %}

blogs/templates/create_blog_post.html
{% extends "layout/fullPageScroll.html" %}

{% block pageContent %}
<form action="{% url 'blogs:create_blog_post' %}"  method="POST" >
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create Blog Post">
</form>
{% endblock %}

blogs/templates/edit_blog_post.html
{% extends "layout/fullPageScroll.html" %}

{% block pageContent %}
<form action="{% url 'blogs:edit_blog_post' pk %}"  method="POST" >
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save Edits" >
</form>
{% endblock %}

blogs/templates/link_list.html
<h3 class="blog-link-title">Blog Posts</h3>
  <ul>
    {% for post in posts %}
    <li>
      <a class="text-button" href="{% url 'blogs:blog_post' post.id %}?page={{ page }}">
          {{ post.title }}
      </a>
    </li>
    {% endfor %}
  </ul>

    <!-- Pagination links -->
    <div class="pagination">
      {% if posts.has_previous %}
        <a href="?page={{ posts.previous_page_number }}">Previous</a>
      {% endif %}
      
      {% for num in posts.paginator.page_range %}
        {% if num == posts.number %}
          <span class="current">{{ num }}</span>
        {% else %}
          <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
      
      {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}">Next</a>
      {% endif %}
    </div>

blogs/templates/success.html
<!DOCTYPE html>
<html>
  <head>
    <title>Success</title>
  </head>
  <body>
    <p>Success!</p>
  </body>
</html>