applications/urls.py
# applications/urls.py
from django.urls import path
from .views import (
    ApplicationDetailView,
    CreateApplicationView,
    ApplicationSuccessView,
    MyApplicationsView,
    JobApplicationsView,
    EditStatusView,
    AcceptApplicantView,
    RejectApplicantView,
    DeleteApplicantView,
)

app_name = 'applications'

urlpatterns = [
    path('applications/<uuid:job_id>/application/<uuid:application_id>/', ApplicationDetailView.as_view(), name='application_detail'),
    path('applications/<uuid:job_id>/application/create/', CreateApplicationView.as_view(), name='create_application'),
    path('applications/<uuid:job_id>/application/<uuid:application_id>/success/', ApplicationSuccessView.as_view(), name='application_success'),
    path('applications/<uuid:job_id>/application/<uuid:application_id>/edit-status/', EditStatusView.as_view(), name='edit_status'),
    path('applications/<uuid:job_id>/application/<uuid:application_id>/accept/', AcceptApplicantView.as_view(), name='accept_applicant'),
    path('applications/<uuid:job_id>/application/<uuid:application_id>/reject/', RejectApplicantView.as_view(), name='reject_applicant'),
    path('applications/<uuid:job_id>/application/<uuid:application_id>/delete/', DeleteApplicantView.as_view(), name='delete_applicant'),
    path('my_applications/', MyApplicationsView.as_view(), name='my_applications'),
    path('applications/<uuid:job_id>/job-applications/', JobApplicationsView.as_view(), name='job_applications'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, HomeCreate, HomeEdit
from django.shortcuts import redirect


urlpatterns = [
    path('', lambda request: redirect('home_view', permanent=True)),
    path('home/', HomeView.as_view(), name='home_view'),
    path('index/', lambda request: redirect('home_view', permanent=True)),
    path('index.html', lambda request: redirect('home_view', permanent=True)),
    path('home/edit/', HomeEdit.as_view(), name='home_edit'),
    path('home/create/', HomeCreate.as_view(), name='home_create'),
]

jobs/urls.py
from django.urls import path
from .views import JobListView, JobDetailView, JobCreateView, JobUpdateView, JobDeleteView

app_name = 'jobs'

urlpatterns = [
    path('jobs/', JobListView.as_view(), name='job_list'),
    path('jobs/<uuid:job_id>/', JobDetailView.as_view(), name='job'),
    path('jobs/create/', JobCreateView.as_view(), name='create_job'),
    path('jobs/<uuid:job_id>/edit/', JobUpdateView.as_view(), name='edit_job'),
    path('jobs/<uuid:job_id>/delete/', JobDeleteView.as_view(), name='delete_job'),
]

main/urls.py
# main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import LoginView, SignupView, LogoutView, PasswordResetRequestView, PasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('blogs.urls')),
    path('', include('applications.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls.orders')),
    path('customers/', include('orders.urls.customers')),
    path('contracts/', include('contracts.urls')),
    path('', include('jobs.urls')),
    path('', include('companies.urls')),
    path('forums/', include('forums.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('generate-prt/', PasswordResetRequestView.as_view(), name='generate_prt'),
    path('reset-password/<str:token>/', PasswordResetView.as_view(), name='reset_password'),
    path('profile/', include('profiles.urls')), 
]

pengin_pi_2/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

jobs/models.py
from django.db import models
import uuid


class Job(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    job_title = models.CharField(max_length=100)
    short_description = models.CharField(max_length=280)
    long_description = models.TextField()
    department = models.CharField(max_length=100)
    salary = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    hiring_manager = models.CharField(max_length=100)
    priority = models.IntegerField(default=10000)
    date_posted = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.job_title
    

jobs/forms.py
# forms.py
from django import forms
from .models import Job

class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['job_title', 'short_description', 'long_description', 'department', 'salary', 'location', 'hiring_manager']
        widgets = {
            'short_description': forms.TextInput(attrs={'placeholder': 'Write a brief description'}),
            # Add other widget customizations if needed
        }

jobs/views.py
import uuid
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator
from django.views import View
from .forms import JobForm
from .models import Job
from util.security.auth_tools import is_admin_provider, is_admin_required

class JobListView(View):
    
    @method_decorator(is_admin_provider)
    def get(self, request, is_admin, *args, **kwargs):
        page = int(request.GET.get('page', 1))
        jobs = Job.objects.all().order_by('priority', '-date_posted')
        paginator = Paginator(jobs, 10)
        jobs_paginated = paginator.get_page(page)

        context = {
            'is_admin': is_admin,
            'jobs': jobs_paginated,
            'page_obj': jobs_paginated,
        }
        return render(request, 'jobs.html', context)

class JobDetailView(View):

    @method_decorator(is_admin_provider)
    def get(self, request, is_admin, job_id, *args, **kwargs):
        job = get_object_or_404(Job, id=job_id)

        # Check if the user is authenticated before performing user-specific logic
        user_applied = False
        user_application_id = None
        if request.user.is_authenticated:
            # Only filter applications for logged-in users
            user_applications = job.applications.filter(user=request.user)
            user_applied = user_applications.exists()
            user_application_id = user_applications.values_list('id', flat=True).first()

        context = {
            'is_admin': is_admin,
            'job': job,
            'user_applied': user_applied,
            'user_application_id': user_application_id,
            'page': 1,
            'primary_title': job.job_title,
        }
        return render(request, 'job.html', context)

    def post(self, request, job_id, *args, **kwargs):
        if not request.user.is_authenticated:
            # Redirect to login if the user is not authenticated
            return redirect('login')

        job = get_object_or_404(Job, id=job_id)
        # Check if the user has already applied
        user_applied = job.applications.filter(user=request.user).exists()

        if user_applied:
            # Return a 403 Forbidden if the user has already applied
            return HttpResponseForbidden("You have already applied for this job.")

        # Additional logic for handling valid application scenario
        return redirect('applications:create_application', job_id=job.id)

class JobCreateView(LoginRequiredMixin, View):
    
    @method_decorator(is_admin_required)
    def get(self, request, *args, **kwargs):
        form = JobForm()
        context = {
            'form': form,
            'primary_title': 'Create Job',
        }
        return render(request, 'job_create.html', context)

    @method_decorator(is_admin_required)
    def post(self, request, *args, **kwargs):
        form = JobForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.date_posted = datetime.now()
            job.save()
            return redirect('job_list')  # Redirect to job list view after creation

        context = {
            'form': form,
            'primary_title': 'Create Job',
        }
        return render(request, 'job_create.html', context)

class JobUpdateView(LoginRequiredMixin, View):
    
    @method_decorator(is_admin_required)
    def get(self, request, job_id, *args, **kwargs):
        job = get_object_or_404(Job, id=job_id)
        form = JobForm(instance=job)
        context = {
            'form': form,
            'job': job,
            'primary_title': 'Edit Job',
        }
        return render(request, 'job_edit.html', context)

    @method_decorator(is_admin_required)
    def post(self, request, job_id, *args, **kwargs):
        job = get_object_or_404(Job, id=job_id)
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            return redirect('job', job_id=job.id)  # Redirect to job detail view after edit

        context = {
            'form': form,
            'job': job,
            'primary_title': 'Edit Job',
        }
        return render(request, 'job_edit.html', context)

class JobDeleteView(LoginRequiredMixin, View):
    
    @method_decorator(is_admin_required)
    def get(self, request, job_id, *args, **kwargs):
        job = get_object_or_404(Job, id=job_id)
        context = {
            'job': job,
        }
        return render(request, 'job_confirm_delete.html', context)

    @method_decorator(is_admin_required)
    def post(self, request, job_id, *args, **kwargs):
        job = get_object_or_404(Job, id=job_id)
        if 'confirm_delete' in request.POST:
            job.delete()
            return redirect('job_list')  # Redirect to job list view after deletion

        # Handle case where confirmation checkbox is not checked
        context = {
            'job': job,
        }
        return render(request, 'job_confirm_delete.html', context)

jobs/templates/job.html
{% extends "layout/fullPageScroll.html" %}
{% load markdownit %}

{% block pageDropDowns %}
  {% if is_admin %}
    <a href="{% url 'jobs:edit_job' job_id=job.id %}">Edit Job</a>
    <form method="post" action="{% url 'jobs:delete_job' job_id=job.id %}">
      {% csrf_token %}
      <input type="checkbox" name="confirm_delete" required> Confirm Delete
      <button type="submit">Delete</button>
    </form>
  {% else %}
    {% if request.user.is_authenticated %}
      <a href="{% url 'applications:create_application' job_id=job.id %}">Apply</a>  <!-- Corrected URL namespace -->
      <a href="{% url 'applications:my_applications' %}">My Applications</a>
    {% endif %}
  {% endif %}
{% endblock %}

{% block pageContent %}
    <p>Job Title: {{ job.job_title }}</p>
    <p>Posted on {{ job.date_posted|date:"F d, Y" }}</p>
    <div class="commonmark">Description: {{ job.short_description|markdownit }}</div>
    <p>Department: {{ job.department }}</p>
    <p>Salary: {{ job.salary }}</p>
    <p>Location: {{ job.location }}</p>
    <p>Hiring Manager: {{ job.hiring_manager }}</p>
    <div class="commonmark">More about this job: {{ job.long_description|markdownit }}</div>

    {% if not is_admin and request.user.is_authenticated %}
      {% if not user_applied %}
      <form method="get" action="{% url 'applications:create_application' job_id=job.id %}">
          <button type="submit">Apply</button>
      </form>
      {% else %}
      <p>You have already applied for this job. 
        <a href="{% url 'applications:application_detail' job_id=job.id application_id=user_application_id %}">
            View Application
        </a>
    </p>
      {% endif %}
    {% elif is_admin %}
      {% if applications.count == 0 %}
        <p>This job has received 0 applications.</p>
      {% elif applications.count == 1 %}
        <p>This job has received 1 application.</p>
        <a href="{% url 'applications:job_applications' job_id=job.id %}">View Applications</a>
      {% else %}
        <p>This job has received {{ applications.count }} applications.</p>
        <a href="{% url 'applications:job_applications' job_id=job.id %}">View Applications</a>
      {% endif %}
    {% endif %}
{% endblock %}

jobs/templates/job_confirm_delete.html
{% extends "layout/fullPageScroll.html" %}

{% block pageContent %}
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ job.job_title }}"?</p>
    <input type="checkbox" name="confirm_delete" required> Confirm deletion<br>
    <button class="primary-button" type="submit">Confirm Delete</button>
    <a href="{% url 'job_list' %}">Cancel</a>
  </form>
{% endblock %}

jobs/templates/job_create.html
{% extends "layout/fullPageScroll.html" %}

{% block pageContent %}
  <form class="form" method="POST" action="{% url 'jobs:create_job' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="primary-button">Create Job</button>
  </form>
{% endblock %}

jobs/templates/job_edit.html
{% extends "layout/fullPageScroll.html" %}

{% block pageContent %}
  <form class="form" method="POST" action="{% url 'jobs:edit_job' job.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="primary-button">Update</button>
  </form>
{% endblock %}

jobs/templates/jobs.html
{% extends "layout/fullPageScroll.html" %}
{% load macros %}
{% loadmacros 'macros/pagination.html' %}

{% block pageDropDowns %}
  {% if is_admin %}
    <a href="{% url 'jobs:create_job' %}">New Job</a> <!-- Ensure the namespace is used -->
  {% else %}
    <a href="{% url 'applications:my_applications' %}">My Applications</a> <!-- Ensure the correct namespace is used -->
  {% endif %}
{% endblock %}

{% block pageContent %}
  <div class="job-grid">
    {% for job in jobs %}
      <a href="{% url 'jobs:job' job_id=job.id %}"> <!-- Corrected to include the 'jobs' namespace -->
        <div>{{ job.job_title }}</div>
        <div>Posted on {{ job.date_posted|date:"F d, Y" }}</div>    
      </a>
    {% endfor %}
  </div>

  {% use_macro render_pagination page_obj %}
{% endblock %}