events/urls.py
from django.urls import path
from .views import CalendarMonth, CreateEvent, DetailEvent, EditEvent, DeleteEvent

# Add namespace to urls
app_name = 'calendar'

urlpatterns = [
    path('', CalendarMonth.as_view(), name='calendar'),
    path('<int:year>/<int:month>/', CalendarMonth.as_view(), name='calendar-month'),
    path('create_event/', CreateEvent.as_view(), name='create-event'),
    path('<uuid:event_id>/', DetailEvent.as_view(), name='detail-event'),
    path('<uuid:event_id>/copy/', CreateEvent.as_view(), name='copy-event'),
    path('<uuid:event_id>/edit/', EditEvent.as_view(), name='edit-event'),
    path('<uuid:event_id>/delete/', DeleteEvent.as_view(), name='delete-event'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, HomeCreate, HomeEdit
from django.shortcuts import redirect


urlpatterns = [
    path('', lambda request: redirect('home_view', permanent=True)),
    path('home/', HomeView.as_view(), name='home_view'),
    path('index/', lambda request: redirect('home_view', permanent=True)),
    path('index.html', lambda request: redirect('home_view', permanent=True)),
    path('home/edit/', HomeEdit.as_view(), name='home_edit'),
    path('home/create/', HomeCreate.as_view(), name='home_create'),
]

main/urls.py
# main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import LoginView, SignupView, LogoutView, PasswordResetRequestView, PasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('blogs.urls')),
    path('', include('applications.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls.orders')),
    path('customers/', include('orders.urls.customers')),
    path('contracts/', include('contracts.urls')),
    path('', include('jobs.urls')),
    path('', include('companies.urls')),
    path('forums/', include('forums.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('generate-prt/', PasswordResetRequestView.as_view(), name='generate_prt'),
    path('reset-password/<str:token>/', PasswordResetView.as_view(), name='reset_password'),
    path('profile/', include('profiles.urls')), 
]

pengin_pi_2/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

events/models.py
from django.db import models
import uuid

from main.models import User
from forums.models import Role  # Role should be in the main app, not in forums


class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    date_created = models.DateTimeField(auto_now_add=True)
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    title = models.CharField(max_length=50)
    description = models.TextField()
    location = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name="authored_events")
    organizer = models.ForeignKey(User, on_delete=models.PROTECT, related_name="organized_events")
    participants = models.ManyToManyField(User, related_name="events", blank=True)
    roles = models.ManyToManyField(Role, related_name="events", blank=True)

    def __str__(self):
        return self.title + " at " + self.location

    def start_date(self):
        return self.start_datetime.date()

    def end_date(self):
        return self.end_datetime.date()

    def start_time(self):
        return self.start_datetime.time().strftime("%H:%M")

    def end_time(self):
        return self.end_datetime.time().strftime("%H:%M")

events/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            "title",
            "description",
            "location",
            "start_datetime",
            "end_datetime",
            "organizer",
            "participants",
            "roles",
        ]
        widgets = {
            "start_datetime": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "end_datetime": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }

events/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View

from .models import Event

from .calendar import EventCalendar
from .forms import EventForm
from .permissions import can_create_or_see_event, can_change_event
from datetime import datetime

myCal = EventCalendar()


class CalendarMonth(View):
    template_name = "calendar/calendar_month.html"

    @method_decorator(login_required)
    def get(self, request, year=None, month=None):
        present_datetime = datetime.now()
        present_year = present_datetime.year
        present_month = present_datetime.month

        if year is None or month is None:
            year = present_year
            month = present_month

        calendar_html = myCal.formatmonth(int(year), int(month), withyear=True, current_user=request.user)

        def get_previous_month():
            if int(month) == 1:
                return {"year": int(year) - 1, "month": 12}
            return {"year": year, "month": int(month) - 1}

        def get_next_month():
            if int(month) == 12:
                return {"year": int(year) + 1, "month": 1}
            return {"year": year, "month": int(month) + 1}

        previous_month = get_previous_month()
        next_month = get_next_month()

        url_previous_month = reverse(
            "calendar:calendar-month",
            kwargs={
                "year": previous_month["year"],
                "month": previous_month["month"],
            },
        )
        url_present_month = reverse(
            "calendar:calendar-month",
            kwargs={
                "year": present_year,
                "month": present_month,
            },
        )
        url_next_month = reverse(
            "calendar:calendar-month",
            kwargs={
                "year": next_month["year"],
                "month": next_month["month"],
            },
        )

        return render(
            request,
            self.template_name,
            {
                "primary_title": "Calendar",
                "calendar_html": calendar_html,
                "url_previous_month": url_previous_month,
                "url_present_month": url_present_month,
                "url_next_month": url_next_month,
                "currentUser": request.user,
            },
        )


class DetailEvent(UserPassesTestMixin, View):
    template_name = "calendar/event_detail.html"

    def test_func(self):
        return can_create_or_see_event(self.request, self.kwargs.get("event_id"))

    @method_decorator(login_required)
    def get(self, request, event_id):
        event = get_object_or_404(Event, id=event_id)
        return render(
            request,
            self.template_name,
            {
                "primary_title": event.title,
                "event": event,
                "can_change": can_change_event(request, event_id)
            },
        )


class CreateEvent(UserPassesTestMixin, View):
    template_name = "calendar/event_form.html"

    def test_func(self):
        return can_create_or_see_event(self.request, self.kwargs.get("event_id"))

    def get_context_data(self, **kwargs):
        return {
            "primary_title": "Create Event",
            "action": "create",
            "form": EventForm(initial=self.get_initial()),
        }

    def get_initial(self):
        if "event_id" in self.kwargs:
            event = get_object_or_404(Event, id=self.kwargs["event_id"])
            return {
                "title": event.title,
                "description": event.description,
                "location": event.location,
                "organizer": event.organizer,
                "participants": event.participants.all,
                "roles": event.roles.all,
                "start_datetime": event.start_datetime,
                "end_datetime": event.end_datetime,
            }
        return {}

    @method_decorator(login_required)
    def get(self, request, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request, **kwargs):
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.author = request.user
            event.save()
            return redirect("calendar:calendar")

        context = self.get_context_data()
        context["form"] = form
        return render(request, self.template_name, context)


class EditEvent(UserPassesTestMixin, View):
    template_name = "calendar/event_form.html"

    def test_func(self):
        return can_change_event(self.request, self.kwargs.get("event_id"))

    def get_context_data(self):
        event = get_object_or_404(Event, id=self.kwargs["event_id"])
        return {
            "primary_title": "Edit Event",
            "action": "update",
            "form": EventForm(instance=event),
            "event": event,
        }

    @method_decorator(login_required)
    def get(self, request, event_id):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request, event_id):
        event = get_object_or_404(Event, id=event_id)
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event = form.save()
            return redirect("calendar:detail-event", event_id=event.id)

        context = self.get_context_data()
        context["form"] = form
        return render(request, self.template_name, context)


class DeleteEvent(UserPassesTestMixin, View):
    template_name = "calendar/event_confirm_delete.html"

    def test_func(self):
        return can_change_event(self.request, self.kwargs.get("event_id"))

    @method_decorator(login_required)
    def get(self, request, event_id):
        event = get_object_or_404(Event, id=event_id)
        context = {
            "primary_title": f"Delete Event: {event.title}",
            "event": event,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required)
    def post(self, request, event_id):
        event = get_object_or_404(Event, id=event_id)
        event.delete()
        return redirect('calendar:calendar')

events/templates/calendar/calendar_month.html
{% extends "layout/fullPageScroll.html" %}

{% block pageDropDowns%}
  <a href="{% url "calendar:create-event" %}">Create Event</a>
{#  <a href="/calendar/settings">Calendar Settings</a>#}
{% endblock %}

{#{% block content %}#}
{% block pageContent %}

<div class="calendar-month">
  <section class="calendar-month-header">
    <div
      id="selected-month"
      class="calendar-month-header-selected-month"
    ></div>
    <section class="calendar-month-header-selectors">
      <a id="previous-month-selector" href="{{ url_previous_month }}"><</a>
      <a id="present-month-selector" href="{{ url_present_month }}">Today</a>
      <a id="next-month-selector" href="{{ url_next_month }}">></a>
    </section>
  </section>

    <div>{{ calendar_html | safe }}</div>
</div>

{% endblock %}

events/templates/calendar/create_event.html
{% extends "layout/fullPageScroll.html" %}

{% block pageDropDowns %}
    {%  if event is defined %}
        <a href="/calendar/{{ event.id }}">Cancel</a>
    {%  else  %}
        <a href="/calendar">Cancel</a>
    {%  endif %}
{% endblock %}

{% block pageContent %}
    <form class="form" method="POST">
        {% if form.errors %}
            <div class="alert alert-danger">
                {% for error in form.errors %}
                    <ul>
                        <li>{{ error}}</li>
                    </ul>
                {% endfor %}
            </div>
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}

        {% if action == "update" %}
            <a href="{% url "calendar:detail-event" event.id %}">
                <button class="primary-button" type="button">Cancel</button>
            </a>
                <button class="primary-button" type="submit">Save changes</button>
        {% else %}
            <a href="{% url "calendar:calendar" %}">
                <button class="primary-button" type="button">Cancel</button>
            </a>
            <button class="primary-button" type="submit">Add Event</button>
        {% endif %}

    </form>
{% endblock %}

events/templates/calendar/detail_event.html
{% extends "layout/fullPageScroll.html" %}

{% block pageDropDowns %}
  <a href="{% url "calendar:create-event" %}">Create Event</a>
  <a href="{% url "calendar:edit-event" event.id %}">Edit Event</a>
  <a href="{% url "calendar:copy-event" event.id %}">Duplicate Event</a>
{#  <a href="{% url "calendar:delete-event" %}">Delete Event</a>#}
{% endblock %}

{% block pageContent %}
<div class="post-container">
    <div class="title-underline">
        <h2 class="post-title">{{ event.title }}</h2>
        <p class="post-info">Created by {{ event.author }} @ {{ event.date_created }}</p>
    </div>
    <p class="post-info">Organizer: {{ event.organizer }}</p>
    <p class="post-info">Start time: {{ event.start_date }} @ {{ event.start_time }}</p>
    <p class="post-info">End time: {{ event.end_date }} @ {{ event.end_time }}</p>
    {% if event.description %}
        <p class="post-info">Description: {{ event.description }}</p>
    {% endif %}
    {% if event.location %}
        <p class="post-info">Location: {{ event.location }}</p>
    {% endif %}
    {% if event.participants.all|length > 0 %}
        <p>Roles:</p>
        {% for role in event.roles.all %}
            <p class="post-info">{{ role }}</p>
        {% endfor %}
    {% endif %}
    {% if event.participants.all|length > 0 %}
        <p>Participants: </p>
        {% for participant in event.participants.all %}
            <p class="post-info">{{ participant }}</p>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

events/templates/calendar/event_confirm_delete.html
{% extends "layout/fullPageScroll.html" %}

{% block pageContent %}
    <p>Do you really want to delete this event?</p>
    <p>{{ event.title }}</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url "calendar:detail-event" event.id %}">
            <button class="primary-button" type="button">Cancel</button>
        </a>
        <button class="primary-button" type="submit">Delete</button>
    </form>
{% endblock %}

events/templates/calendar/event_detail.html
{% extends "layout/fullPageScroll.html" %}

{% block pageDropDowns %}
    <a href="{% url "calendar:create-event" %}">Create Event</a>
    <a href="{% url "calendar:copy-event" event.id %}">Duplicate Event</a>
    {% if can_change %}
        <a href="{% url "calendar:edit-event" event.id %}">Edit Event</a>
        <a href="{% url "calendar:delete-event" event.id %}">Delete Event</a>
    {% endif %}
{% endblock %}

{% block pageContent %}
<div class="post-container">
    <div class="title-underline">
        <h2 class="post-title">{{ event.title }}</h2>
        <p class="post-info">Created by {{ event.author }} @ {{ event.date_created }}</p>
    </div>
    <p class="post-info">Organizer: {{ event.organizer }}</p>
    <p class="post-info">Start time: {{ event.start_date }} @ {{ event.start_time }}</p>
    <p class="post-info">End time: {{ event.end_date }} @ {{ event.end_time }}</p>
    {% if event.description %}
        <p class="post-info">Description: {{ event.description }}</p>
    {% endif %}
    {% if event.location %}
        <p class="post-info">Location: {{ event.location }}</p>
    {% endif %}
    {% if event.participants.all|length > 0 %}
        <p>Roles:</p>
        {% for role in event.roles.all %}
            <p class="post-info">{{ role }}</p>
        {% endfor %}
    {% endif %}
    {% if event.participants.all|length > 0 %}
        <p>Participants: </p>
        {% for participant in event.participants.all %}
            <p class="post-info">{{ participant }}</p>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

events/templates/calendar/event_form.html
{% extends "layout/fullPageScroll.html" %}

{% block pageDropDowns %}
    {%  if action == "update" %}
        <a href="{% url "calendar:detail-event" event.id %}">Cancel</a>
    {%  else  %}
        <a href="{% url "calendar:calendar" %}">Cancel</a>
    {%  endif %}
{% endblock %}

{% block pageContent %}
    <form class="form" method="POST">
        {% if form.errors %}
            <div class="alert alert-danger">
                {% for error in form.errors %}
                    <ul>
                        <li>{{ error }}</li>
                    </ul>
                {% endfor %}
            </div>
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}

        {% if action == "update" %}
            <a href="{% url "calendar:detail-event" event.id %}">
                <button class="primary-button" type="button">Cancel</button>
            </a>
                <button class="primary-button" type="submit">Save changes</button>
        {% else %}
            <a href="{% url "calendar:calendar" %}">
                <button class="primary-button" type="button">Cancel</button>
            </a>
            <button class="primary-button" type="submit">Add Event</button>
        {% endif %}

    </form>
{% endblock %}